<a href="https://colab.research.google.com/github/shaikhmahek82218-cmd/-Task1-Data-Analysis-with-Python/blob/main/Task_1_Data_Cleaning_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

print("Pandas imported successfully!")

Pandas imported successfully!

In [2]:
data = {
    "Name": ["Aman", "Priya", "Rahul", "Sneha", "Aman", "Vikas", "Neha", "Riya"],
    "Age": [22, 25, np.nan, 24, 22, 28, 23, 26],
    "Salary": [25000, 32000, 28000, np.nan, 25000, 45000, 30000, 35000],
    "City": ["Pune", "Mumbai", "Pune", "Delhi", "Pune", "Mumbai", "Delhi", "Pune"]
}

df = pd.DataFrame(data)

df

    Name   Age   Salary    City
0   Aman  22.0  25000.0    Pune
1  Priya  25.0  32000.0  Mumbai
2  Rahul   NaN  28000.0    Pune
3  Sneha  24.0      NaN   Delhi
4   Aman  22.0  25000.0    Pune
5  Vikas  28.0  45000.0  Mumbai
6   Neha  23.0  30000.0   Delhi
7   Riya  26.0  35000.0    Pune

In [3]:
print("First 5 rows:")
display(df.head())

print("\nDataset Information:")
df.info()

First 5 rows:

    Name   Age   Salary    City
0   Aman  22.0  25000.0    Pune
1  Priya  25.0  32000.0  Mumbai
2  Rahul   NaN  28000.0    Pune
3  Sneha  24.0      NaN   Delhi
4   Aman  22.0  25000.0    Pune

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Age     7 non-null      float64
 2   Salary  7 non-null      float64
 3   City    8 non-null      object
dtypes: float64(2), object(2)
memory usage: 388.0+ bytes

In [4]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Name      0
Age       1
Salary    1
City      0
dtype: int64

In [5]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Salary"] = df["Salary"].fillna(df["Salary"].median())

print("Missing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
Name      0
Age       0
Salary    0
City      0
dtype: int64

In [6]:
df = df.drop_duplicates()

print("Duplicates after cleaning:")
print(df.duplicated().sum())

Duplicates after cleaning:
0

In [7]:
print("Statistical Summary:")
df.describe()

Statistical Summary:

             Age        Salary
count   7.000000      7.000000
mean   24.571429  32142.857143
std     1.988060   6466.028442
min    22.000000  25000.000000
25%    23.500000  29000.000000
50%    24.000000  30000.000000
75%    25.500000  33500.000000
max    28.000000  45000.000000

In [8]:
print("Number of people from each city:")
print(df["City"].value_counts())

Number of people from each city:
City
Pune      3
Mumbai    2
Delhi     2
Name: count, dtype: int64

In [9]:
print("Final Cleaned Dataset:")
display(df)

print("Shape of dataset:", df.shape)

Final Cleaned Dataset:

    Name   Age   Salary    City
0   Aman  22.0  25000.0    Pune
1  Priya  25.0  32000.0  Mumbai
2  Rahul  24.0  28000.0    Pune
3  Sneha  24.0  30000.0   Delhi
5  Vikas  28.0  45000.0  Mumbai
6   Neha  23.0  30000.0   Delhi
7   Riya  26.0  35000.0    Pune

Shape of dataset: (7, 4)

In [10]:
print("Conclusion:")
print("The dataset was successfully cleaned and explored.")
print("Missing values were handled and duplicate records were removed.")
print("Basic statistical and categorical analysis was performed.")

Conclusion:
The dataset was successfully cleaned and explored.
Missing values were handled and duplicate records were removed.
Basic statistical and categorical analysis was performed.